export const queryKeys = {
  TODOS: 'TODOS',
  STATISTICS: 'STATISTICS',
  GET_TODOLIST: 'GET_TODOLIST',
  CREATE_TODO: 'CREATE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  DELETE_TODO_FORCE: 'DELETE_TODO_FORCE',
  GET_TODOLIST_STATISTICS: 'GET_TODOLIST_STATISTICS',
} as const;
