export const queryKeys = {
  GET_TODOLIST: 'GET_TODOLIST',
  CREATE_TODO: 'CREATE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  DELETE_TODO_FORCE: 'DELETE_TODO_FORCE',
} as const;
