name: CI

on:
  pull_request:
    types: [opened, assigned, synchronize, labeled]

defaults:
  run:
    working-directory: ./

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          dry: True
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
