name: GitLab Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1.1.0
        with:
          target_repo_url: git@git.swmgit.org:swm-13-main/13_swm77/mozi-client.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
